'use strict';

/**
 * DSH Status Pet -Electron main process.
 *
 * Owns one frameless, transparent, always-on-top window that draws the pet in
 * its bottom-right corner, follows the live Harness session journal through
 * {@link StatusReader}, and persists the user's display settings.
 *
 * @module main
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const { app, BrowserWindow, Menu, Tray, ipcMain, nativeImage, net, protocol, screen, shell } = require('electron');
const { pathToFileURL } = require('url');

const { StatusReader } = require('./status-reader');
const { DEFAULTS, PET_ASPECT, normalizeSettings, loadSettings, saveSettings } = require('./settings');
const { currentBounds: placeBounds, resolveSnap, shouldMirror } = require('./placement');
const { buildMenu } = require('./menu');

/** Asset directory shared with the renderer through the `pet-asset://` scheme. */
const ASSET_DIR = path.join(__dirname, '..', '..', 'assets');
/** Multi-resolution Windows icon built by `tools/make_app_icon.py`. */
const APP_ICON = path.join(ASSET_DIR, 'app.ico');
/** Tray icon: the pet's face, downscaled to 32px. */
const TRAY_ICON = path.join(ASSET_DIR, 'tray.png');
/**
 * Last-resort tray icon bytes (a tiny transparent square) for the pathological
 * case where the asset file is missing: a tray with a blank icon still beats no
 * tray at all, and no tray beats a crash.
 */
const TRAY_FALLBACK_PNG = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAEklEQVR42mNkYPhfz0AEYBxVSF+FABJADveWkH6oAAAAAElFTkSuQmCC',
  'base64',
);

// Declared before the app is ready, as the protocol registry requires.
protocol.registerSchemesAsPrivileged([
  { scheme: 'pet-asset', privileges: { standard: true, secure: true, supportFetchAPI: true } },
]);

/**
 * Serve the pet artwork over a private scheme. A `file://` page has an opaque
 * origin, so `img-src 'self'` cannot reach a sibling directory; a registered
 * scheme keeps the page's CSP tight while still loading the real file.
 */
function serveAssets() {
  protocol.handle('pet-asset', (request) => {
    const name = decodeURIComponent(new URL(request.url).pathname).replace(/^[\\/]+/, '');
    const resolved = path.resolve(ASSET_DIR, name);
    if (!resolved.startsWith(ASSET_DIR + path.sep)) {
      return new Response('forbidden', { status: 403 });
    }
    return net.fetch(pathToFileURL(resolved).toString());
  });
}

/** Append one diagnostic line to the app's own log file. */
function log(message) {
  try {
    const file = path.join(app.getPath('userData'), 'pet.log');
    fs.appendFileSync(file, `${new Date().toISOString()} ${message}\n`);
  } catch {
    /* logging must never break the pet */
  }
  if (process.env.DSH_PET_DEBUG === '1') console.log(`[dsh-status-pet] ${message}`);
}

/**
 * Tray icon bytes: the pet's face, generated by `tools/make_app_icon.py` into
 * `assets/tray.png`. The file is read at startup so re-running the script
 * updates the tray without editing code; the inline fallback covers a missing
 * asset.
 */
function trayIconImage() {
  try {
    const image = nativeImage.createFromPath(TRAY_ICON);
    if (!image.isEmpty()) return image;
    log('tray icon file was empty, using the inline fallback');
  } catch (error) {
    log(`tray icon file unreadable: ${error.message}`);
  }
  return nativeImage.createFromBuffer(TRAY_FALLBACK_PNG);
}

/** Idle poll cadence for the journal watcher. */
const POLL_MS = 450;
/**
 * Widget geometry. The bubble sits above the pet's head inside the transparent
 * pocket the asset leaves there, so the window only has to be slightly wider
 * than the pet's own box.
 */
const WIDGET_RATIO = 1.35;

let win = null;
let tray = null;
let reader = null;
let settings = null;
let status = { state: 'idle', sessionId: null, lastError: null };
/** Whether the pet is currently drawn mirrored (left half of the desktop). */
let mirrored = false;
let quitting = false;

function settingsFile() {
  return path.join(app.getPath('userData'), 'settings.json');
}

/** Work area of the display the cursor is on. */
function activeArea() {
  return screen.getDisplayNearestPoint(screen.getCursorScreenPoint()).workArea;
}

/**
 * Work area of the display that currently holds the widget. During a drag the
 * cursor can be on another display, so this is the honest area to compare
 * against when deciding whether the pet is on the left.
 * @returns {{x: number, y: number, width: number, height: number}} work area.
 */
function areaForBounds(bounds) {
  if (win !== null && !win.isDestroyed()) {
    return screen.getDisplayMatching(bounds).workArea;
  }
  return activeArea();
}

/**
 * Recompute the mirror state from the widget's actual position and, when it
 * flips, tell the renderer to animate the pet and its bubble into the new pose.
 * @param {{x: number, y: number, width: number, height: number}} [bounds] - the
 * current window bounds; read from the window when omitted.
 * @param {boolean} [force] - set the state instead of deriving it, so a snap
 * can promise an orientation even on a narrow work area.
 */
function updateMirror(bounds, force) {
  if (win === null || win.isDestroyed()) return;
  const actual = bounds ?? win.getBounds();
  const next = typeof force === 'boolean' ? force : shouldMirror(actual, areaForBounds(actual));
  if (next === mirrored) return;
  mirrored = next;
  pushState();
}

/**
 * Window bounds for the current settings.
 * @param {{keepPosition?: boolean, side?: 'right'|'left'}} [options] - set
 * `keepPosition: false` to ignore any dragged position and re-anchor to a
 * corner; `side` picks which one (bottom-right by default).
 * @returns {{x: number, y: number, width: number, height: number}} bounds.
 */
function currentBounds(options = {}) {
  return placeBounds(settings, activeArea(), PET_ASPECT, options);
}

function createWindow() {
  const bounds = currentBounds();
  win = new BrowserWindow({
    ...bounds,
    transparent: true,
    frame: false,
    resizable: false,
    movable: true,
    hasShadow: false,
    skipTaskbar: true,
    fullscreenable: false,
    maximizable: false,
    minimizable: false,
    alwaysOnTop: true,
    show: false,
    title: 'DSH Status Pet',
    icon: fs.existsSync(APP_ICON) ? APP_ICON : undefined,
    backgroundColor: '#00000000',
    webPreferences: {
      preload: path.join(__dirname, '..', 'preload', 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
      backgroundThrottling: false,
    },
  });

  win.setAlwaysOnTop(true, 'screen-saver');
  win.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true });
  win.loadFile(path.join(__dirname, '..', 'renderer', 'index.html'));
  win.webContents.on('console-message', (_event, level, message, line, source) => {
    log(`renderer[${String(level)}] ${message} (${source}:${String(line)})`);
  });
  win.webContents.on('did-fail-load', (_event, code, description) => {
    log(`renderer failed to load: ${String(code)} ${description}`);
  });
  win.webContents.on('render-process-gone', (_event, details) => {
    log(`renderer gone: ${details.reason}`);
  });
  win.once('ready-to-show', () => {
    mirrored = shouldMirror(win.getBounds(), areaForBounds(win.getBounds()));
    pushState();
    win.showInactive();
    log(`window shown at ${JSON.stringify(win.getBounds())} size=${String(settings.petSize)}`);
  });
  win.on('closed', () => {
    win = null;
  });
  // Belt and braces: Electron reports the move for programmatic changes too, so
  // the mirror state stays correct even if a path forgets to call updateMirror.
  win.on('moved', () => updateMirror());
  // The pet is decorative: never let the page navigate or spawn windows.
  win.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url).catch(() => {});
    return { action: 'deny' };
  });
}

/** Send the current settings, status and mirror state to the renderer. */
function pushState() {
  if (win === null || win.isDestroyed()) return;
  win.webContents.send('pet:state', { settings, status, mirrored });
}

function applySettings(next, { persist = true } = {}) {
  const previous = settings;
  settings = normalizeSettings(next);
  if (persist) saveSettings(settingsFile(), settings);

  if (win !== null && !win.isDestroyed()) {
    if (previous === null) {
      win.setBounds(currentBounds());
    } else if (previous.petSize !== settings.petSize) {
      // A size change re-anchors the widget to the bottom-right corner: keeping
      // the old top-left would push the wider window off the screen.
      const bounds = currentBounds({ keepPosition: false });
      win.setBounds(bounds);
      settings = { ...settings, position: { x: bounds.x, y: bounds.y } };
      if (persist) saveSettings(settingsFile(), settings);
    } else if (previous.margin !== settings.margin) {
      win.setBounds(currentBounds());
    }
    if (previous === null || previous.petVisible !== settings.petVisible) {
      if (settings.petVisible) {
        win.showInactive();
        win.setAlwaysOnTop(true, 'screen-saver');
      } else {
        win.hide();
      }
    }
    if (previous === null || previous.clickThrough !== settings.clickThrough) {
      win.setIgnoreMouseEvents(settings.clickThrough === true, { forward: true });
    }
    updateMirror();
    pushState();
  }
  refreshTrayMenu();
}

/** Merge one partial settings patch from the renderer or a menu. */
function patchSettings(patch) {
  applySettings({ ...settings, ...patch });
}

function refreshTrayMenu() {
  if (tray === null || tray.isDestroyed()) return;
  try {
    tray.setContextMenu(Menu.buildFromTemplate(buildMenu(settings, handlers)));
    tray.setToolTip(`DSH Status Pet: ${status.state}`);
  } catch (error) {
    // A tray whose native handle is not ready yet rejects the first assignment;
    // the retry below lands once the shell has finished creating the icon.
    log(`tray menu deferred: ${error.message}`);
    setTimeout(() => {
      if (tray === null || tray.isDestroyed()) return;
      try {
        tray.setContextMenu(Menu.buildFromTemplate(buildMenu(settings, handlers)));
      } catch (retryError) {
        log(`tray menu unavailable: ${retryError.message}`);
      }
    }, 1200);
  }
}

/**
 * Move the widget to one bottom corner and set its orientation to match: the
 * bottom-right corner is the default pose, the bottom-left corner the mirrored
 * one. The stored drag position has to be dropped, otherwise re-applying it
 * would land the widget exactly where it already was.
 * @param {'right'|'left'} side - which corner to snap to.
 */
function snapToCorner(side) {
  if (win === null || win.isDestroyed()) return;
  const { bounds, mirrored: target } = resolveSnap(settings, activeArea(), PET_ASPECT, side);
  applySettings({ ...settings, petVisible: true, position: null });
  win.setBounds(bounds);
  win.showInactive();
  // Forced, not derived: a left snap must end up mirrored even when the work
  // area is too narrow for the widget's centre to fall on the left half.
  updateMirror(bounds, target);
  log(`snapped to bottom-${side} at ${JSON.stringify(bounds)} mirrored=${String(target)}`);
}

const handlers = {
  patch: (patch) => patchSettings(patch),
  quit: () => {
    quitting = true;
    app.quit();
  },
  reset: () => {
    applySettings({ ...DEFAULTS, position: null });
    if (win !== null && !win.isDestroyed()) win.setBounds(currentBounds({ keepPosition: false }));
  },
  resetRight: () => snapToCorner('right'),
  resetLeft: () => snapToCorner('left'),
};

function createTray() {
  try {
    const icon = trayIconImage();
    if (icon.isEmpty()) throw new Error('tray icon decoded to an empty image');
    tray = new Tray(icon);
    tray.on('click', () => {
      if (win === null || win.isDestroyed()) return;
      if (settings.petVisible && win.isVisible()) {
        applySettings({ ...settings, petVisible: false });
      } else {
        applySettings({ ...settings, petVisible: true });
      }
    });
    refreshTrayMenu();
    log('tray ready');
  } catch (error) {
    tray = null;
    log(`tray unavailable: ${error.message}`);
  }
}

function startReader() {
  const dshHome = process.env.DSH_HOME || path.join(os.homedir(), '.dsh');
  reader = new StatusReader({ dshHome, intervalMs: POLL_MS });
  reader.on('error', (error) => log(`reader error: ${error.message}`));
  reader.on('status', (next) => {
    const changed = next.state !== status.state || next.lastError !== status.lastError;
    status = next;
    if (changed) {
      log(`status -> ${next.state}${next.lastError === null ? '' : ` (${String(next.lastError).slice(0, 80)})`}`);
      pushState();
      refreshTrayMenu();
    }
  });
  reader.start();
  log(`reader started on ${dshHome} state=${reader.snapshot().state}`);
}

function registerIpc() {
  ipcMain.handle('pet:hello', () => ({ settings, status, mirrored, version: app.getVersion() }));
  ipcMain.on('pet:patch', (_event, patch) => {
    if (patch !== null && typeof patch === 'object') patchSettings(patch);
  });
  ipcMain.on('pet:menu', () => {
    const menu = Menu.buildFromTemplate(buildMenu(settings, handlers, { standalone: true }));
    menu.popup({ window: win ?? undefined });
  });
  // The pet's own "snap to a corner" action, shared with the menu and the tray.
  ipcMain.on('pet:snap', (_event, side) => handlers[side === 'left' ? 'resetLeft' : 'resetRight']());
  ipcMain.on('pet:drag', (_event, delta) => {
    if (win === null || win.isDestroyed() || delta === null || typeof delta !== 'object') return;
    const [x, y] = win.getPosition();
    const nx = Math.round(x + (Number(delta.dx) || 0));
    const ny = Math.round(y + (Number(delta.dy) || 0));
    win.setPosition(nx, ny);
    settings = { ...settings, position: { x: nx, y: ny } };
    // Decide the mirror state while dragging, not only at the end, so the flip
    // happens the moment the pet crosses the middle of the desktop.
    updateMirror(win.getBounds());
  });
  ipcMain.on('pet:drag-end', () => {
    saveSettings(settingsFile(), settings);
    // Falling back to the default anchor keeps the pet findable after a drag.
    const bounds = win === null || win.isDestroyed() ? null : win.getBounds();
    if (bounds !== null) settings = { ...settings, position: { x: bounds.x, y: bounds.y } };
    updateMirror(bounds ?? undefined);
  });
}

const singleInstance = app.requestSingleInstanceLock();
if (!singleInstance) {
  app.quit();
} else {
  // A failure in a timer or an event handler must not pop Electron's error
  // dialog over the user's desktop; the log keeps the detail instead.
  process.on('uncaughtException', (error) => {
    log(`uncaught exception: ${error.stack ?? error.message}`);
  });
  process.on('unhandledRejection', (reason) => {
    log(`unhandled rejection: ${reason instanceof Error ? (reason.stack ?? reason.message) : String(reason)}`);
  });

  app.on('second-instance', () => handlers.resetRight());

  app.whenReady().then(() => {
    app.setAppUserModelId('dev.dsh.status-pet');
    // Privileged schemes must be declared before the app is ready to be usable
    // by pages; the standard/secure flags keep it out of the web security path.
    serveAssets();
    settings = loadSettings(settingsFile());
    createWindow();
    createTray();
    registerIpc();
    startReader();
    // A display change (unplugged monitor, resolution switch) must not strand
    // the pet off screen; it can also change which half of the desktop the pet
    // is standing on.
    screen.on('display-metrics-changed', () => {
      if (win === null || win.isDestroyed()) return;
      win.setBounds(currentBounds());
      updateMirror();
    });
    screen.on('display-removed', () => {
      if (win === null || win.isDestroyed()) return;
      win.setBounds(currentBounds());
      updateMirror();
    });
  });

  app.on('window-all-closed', () => {
    if (!quitting) app.quit();
  });

  app.on('before-quit', () => {
    quitting = true;
    if (reader !== null) reader.stop();
  });
}

